# Generated by Django 5.1.7 on 2025-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_post_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage="portfolio.storages.RawMediaCloudinaryStorage",
                upload_to="blog_files/",
            ),
        ),
    ]
